name: bus_arrival
description: A minimalist bus tracker app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  intl: ^0.17.0
  location: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter:
  uses-material-design: true
  assets:
    - stops.json
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/bus.png"
  min_sdk_android: 21
